### ISSUE TITLE
无法获取种子列表

### ISSUE THREAD

**Issue by xieshang3p** [lipssmycode/byrbt_bot#10]
RT
![image](https://user-images.githubusercontent.com/80677011/121862754-b4794180-cd2d-11eb-8435-f8fb0393469a.png)

账号密码正确，服务器设置了ipv6优先，cookie的文件也存在，无法获取种子列表(

**Comment by WhymustIhaveaname** [comment]
这其实是主页免费并且有人在下载的种子的列表，为空是正常的。

我重新写了交互部分，相信能澄清一些东西 https://github.com/WhymustIhaveaname/byrbt_bot

**Comment by WhymustIhaveaname** [comment]
这个仓库刚刚惹毛我了，详见 https://github.com/lipssmycode/byrbt_bot/issues/12

**Comment by lipssmycode** [comment]
确实是因为免费种子太多了，会提高过滤条件
