### ISSUE TITLE
在 requirements.txt 中添加 Cython

### ISSUE THREAD

**Issue by WhymustIhaveaname** [lipssmycode/byrbt_bot#11]
没有 Cython 会导致 scikit-learn 无法安装，这费了我一点时间。

**Comment by WhymustIhaveaname** [comment]
整个 requirements 似乎都过时了，lxml 也不识别，最后我一个个手动安装的。

**Comment by peroperotina** [comment]
那能麻烦您分享一下requirements.txt吗   萌新也遇到这些问题了

**Comment by lipssmycode** [comment]
> 那能麻烦您分享一下requirements.txt吗 萌新也遇到这些问题了

有报错截图吗，还有你的安装环境是怎样的，因为我这边用miniconda安装的环境，可能没有遇到这些问题

**Comment by lipssmycode** [comment]
@peroperotina 更新了一下requirements.txt，把Cpython这个注释去掉安装应该可行

**Comment by peroperotina** [comment]
> @peroperotina 更新了一下requirements.txt，把Cpython这个注释去掉安装应该可行

你好..requirements.txt应该不允许中间插入"#注释"..会报错的

**Comment by lipssmycode** [comment]
@peroperotina  啊，确实，我改改，谢谢提醒

**Comment by peroperotina** [comment]
@lipssmycode 萌新仔细测试了一下 应该只是不支持utf-8的原因  中间插入英文注释就没事
这是使用原来带有"#关于cython的中文注释"时的报错截图
![Snipaste_2022-06-11_14-25-51](https://user-images.githubusercontent.com/25301986/173176299-9cca3c94-e036-444f-8eda-38126085eb57.png)

**Comment by peroperotina** [comment]
> @peroperotina 啊，确实，我改改，谢谢提醒

能不能用scikit-learn 1.1.1版本啊
requirements里的0.21.3无法安装
这是错误日志
[log.txt](https://github.com/lipssmycode/byrbt_bot/files/8883406/log.txt)

**Comment by lipssmycode** [comment]
@peroperotina 仔细看错误，是缺少Microsoft Visual C++ 14.0了安装一下就行

**Comment by peroperotina** [comment]
> @peroperotina 仔细看错误，是缺少Microsoft Visual C++ 14.0了安装一下就行；这个版本我不好改动，因为是[decaptcha(https://github.com/bumzy/decaptcha)](https://github.com/bumzy/decaptcha)项目使用的，其他版本的scikit-learn不保证模型能使用

我把visual studio的c++ build tools安全齐依然不行 [参考stackOverflow](https://stackoverflow.com/questions/70583969/pyinstaller-no-module-named-numpy-distutils)疑似是因为高版本(我是python3.10.5)的python的pyinstaller不兼容scikit-learn==0.21.3的依赖
我主动降级到 python3.7.9后可以正常安装依赖了然后正常运行了(可喜可贺)

**Comment by lipssmycode** [comment]
> > @peroperotina 仔细看错误，是缺少Microsoft Visual C++ 14.0了安装一下就行；这个版本我不好改动，因为是[decaptcha(https://github.com/bumzy/decaptcha)](https://github.com/bumzy/decaptcha)项目使用的，其他版本的scikit-learn不保证模型能使用
> 
> 我把visual studio的c++ build tools安装齐全了依然不行 [参考stackOverflow](https://stackoverflow.com/questions/70583969/pyinstaller-no-module-named-numpy-distutils)疑似是因为高版本(我是python3.10.5)的python的pyinstaller不兼容scikit-learn==0.21.3的依赖 我主动降级到 python3.7.9后可以正常安装依赖了然后正常运行了(可喜可贺)
> 
> 现在一直在重复: scan torrent list... available list:(none)
> 
> 希望bot早日开始干活

注意下首先机器得能链接https://byr.pt/，不然bot是无法使用的。另外有问题再问我吧，祝使用愉快！
