### ISSUE TITLE
你不强调这个机器人会删除文件，一上来连警告都没有就把我1个T的文件给删了！！！

### ISSUE THREAD

**Issue by WhymustIhaveaname** [lipssmycode/byrbt_bot#12]
详见 https://github.com/WhymustIhaveaname/byrbt_bot
![image](https://user-images.githubusercontent.com/38423345/125344027-5b7ee680-e389-11eb-8e3d-5f4310e58138.png)

**Comment by WhymustIhaveaname** [comment]
![image](https://user-images.githubusercontent.com/38423345/125343259-713fdc00-e388-11eb-8f01-814b881bf3c7.png)
这代码有一点用吗？`in ('Windows','Linux')` 它不香吗？

**Comment by WhymustIhaveaname** [comment]
![image](https://user-images.githubusercontent.com/38423345/125343345-8b79ba00-e388-11eb-9963-4dec2a3a3312.png)
代码最重要的就是复用，你把几乎一样的东西写两遍自己不难受吗？

**Comment by WhymustIhaveaname** [comment]
![image](https://user-images.githubusercontent.com/38423345/125343428-a2201100-e388-11eb-90ff-bb76bc14f94b.png)
你在一个while里一遍遍地sort那个text_s(436行)，然后明明list已经pop了，还单独用一个torren-len存list的长度，我真的傻了

**Comment by lipssmycode** [comment]
只是个简单脚本而已，不喜勿用
