### ISSUE TITLE
修改哪个路径下的transmission的settings..json? 项目目录下的还是用户目录下的？

### ISSUE THREAD

**Issue by peroperotina** [lipssmycode/byrbt_bot#18]
readme中要求我手动启动transmission 那transmission想必是读取用户目录下的json吧
那项目目录\transmission\data下的settings.json是干什么的呢？

**Comment by lipssmycode** [comment]
Readme表述有点问题，我更新了。如果是采用docker部署的话，./transmission/data下的setting.json就是transmission的配置文件。如果是手动部署的话，就需要修改自己部署的transmission的配置，./transmission/data下的配置文件就没用了，可以当做参考

**Comment by peroperotina** [comment]
@lipssmycode 这个bot是和transmission还是transmission deamon交互?
我实在是被这个transmission软件搞的晕晕的

**Comment by lipssmycode** [comment]
@peroperotina 可以看看网上的一些资料，比如https://www.jianshu.com/p/bbd4f6832268?nomobile=yes，bot准确来说是和transmission-daemon的rpc接口交互。正常使用transmission的话应该安装包括transmission-cli和transmission-daemon，一个客户端，一个服务端。

**Comment by peroperotina** [comment]
> @peroperotina 可以看看网上的一些资料，比如[https://www.jianshu.com/p/bbd4f6832268?nomobile=yes，](https://www.jianshu.com/p/bbd4f6832268?nomobile=yes%EF%BC%8C) bot准确来说是和transmission-daemon的rpc接口交互。正常使用transmission的话应该安装包括transmission-cli和transmission-daemon，一个客户端，一个服务端。

那么萌新就差scikit-learn的问题了..安装时提示找不到某个moudule  已经在另一个issue里给出log

**Comment by lipssmycode** [comment]
@peroperotina bot.py fix一个磁盘空间检测bug，需要更新一下
