### ISSUE TITLE
如何让程序更加自动化

### ISSUE THREAD

**Issue by KevinMarkk** [lipssmycode/byrbt_bot#2]
大佬您好，考虑到每次运行byrbt.py时都要输入main之后才能启动主程序，如何能让bot在会话结束后继续在后台运行，而不需要每次都要手动启动bot呢？谢谢！

**Comment by lipssmycode** [comment]
linux用screen开个会话挂后台就行了

**Comment by KevinMarkk** [comment]
多谢大佬指点，之前只想着用nohup了
