### ISSUE TITLE
是否可以支持获取多页的free种子

### ISSUE THREAD

**Issue by RManLuo** [lipssmycode/byrbt_bot#20]
首先感谢您的项目，但有个问题想和您探讨。现在获取种子只获取了第一页的种子信息。是否可以通过`https://byr.pt/torrents.php?page=1`获取多页呢？这样应该可以增加获取到的free种子数量。不知道只获取首页free种子是出于什么考量呢？是只用首页种子的上传就足够了吗？

**Comment by lipssmycode** [comment]
噢，这个问题我的考虑是首页已经存在50个种子了，效率上足够了，原因有几个：1.首先脚本每分钟都会请求一次种子首页，而1分钟内一般不会突然出现50个新种子；2. 用户对首页的关注是最多的，因此首页产生好的种子（上传数远多于下载数的种子）的概率比较大；3. 请求多次页面对服务器压力也较大；4. 限时制定大部分都出现在首页，可以覆盖到

**Comment by RManLuo** [comment]
了解了，感谢您的回复！
