### ISSUE TITLE
docker容器中的bot-1不能运行

### ISSUE THREAD

**Issue by qinghe4444447** [lipssmycode/byrbt_bot#23]
最后一行是这样提示的：
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='byr.pt', port=443): Max retries exceeded with url: /login.php (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd15047bd10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
请问这是为什么

**Comment by lipssmycode** [comment]
网络问题，连不上bt网，首先检查机器本身能不能上bt网，如果可以，检查容器网络模式是不是host模式

**Comment by qinghe4444447** [comment]
两个都可以，network就是host，也可以登录bt站

**Comment by lipssmycode** [comment]
不过这个就是网络问题，建议直接在容器里面访问一下byr，试试看行不行

**Comment by qinghe4444447** [comment]
谢谢，我明天看看

**Comment by qinghe4444447** [comment]
您好，我查了一下，好像是windows和Mac环境下不支持net=host这个参数，我添加了新的ipv6地址也不行，请问需要怎么修改

**Comment by lipssmycode** [comment]
这个不是本项目考虑的问题呀，建议查一下资料能不能解决，我是记得有个利用特殊DNS解决的方式具体细节已经忘记

**Comment by lipssmycode** [comment]
或者不采用docker，直接部署
