### ISSUE TITLE
北邮人pt网页已改版，bot报错

### ISSUE THREAD

**Issue by Dong-Guan-Saohuang-Dadui** [lipssmycode/byrbt_bot#25]
报错如下
`check disk space...
byrbt_bot-bot-1  | scan torrent list...
byrbt_bot-bot-1  | user info:
byrbt_bot-bot-1  | user info not found!
byrbt_bot-bot-1  | [ERROR] AttributeError("'NoneType' object has no attribute 'select_one'")
byrbt_bot-bot-1  | free torrent list：
byrbt_bot-bot-1  | available torrent list：
`

**Comment by Dong-Guan-Saohuang-Dadui** [comment]
```
check disk space...
byrbt_bot-bot-1  | scan torrent list...
byrbt_bot-bot-1  | user info:
byrbt_bot-bot-1  | user info not found!
byrbt_bot-bot-1  | [ERROR] AttributeError("'NoneType' object has no attribute 'select_one'")
byrbt_bot-bot-1  | free torrent list：
byrbt_bot-bot-1  | available torrent list：
```

**Comment by lipssmycode** [comment]
已修复，感谢@RManLuo
