### ISSUE TITLE
新版本语法支持变更

### ISSUE THREAD

**Issue by BobAnkh** [lipssmycode/byrbt_bot#3]
似乎在新的python版本中（我使用的是3.7.6）直接安装完依赖运行会出现如下报错：

![image](https://user-images.githubusercontent.com/44333669/80108603-0f425d80-85af-11ea-8e65-bc063d2c6ccd.png)

我对此做出的解决办法为吧byrbt.py第99行中的`lxml`改成了`html.parser`程序即可正常运行。

是否可以对此做出一些升级或说明？

感谢！

**Comment by lipssmycode** [comment]
这个可能是缺少lxml依赖包吧，建议还是用低版本的python，因为验证码识别模型项目用的python版本就比较低，所以不考虑升级python版本

**Comment by BobAnkh** [comment]
感谢您的答复，不过似乎完成这样的修改之后可以正常运行而并未产生问题，或许这是一种在高python版本下可行的方案。目前初步看来似乎需要在python<3.6的环境下使用（这需要更进一步的测试），所以可否对于使用的python版本进行一些补充说明，以便后续的使用者可以直接选择合适的python版本？

**Comment by lipssmycode** [comment]
我看了一下我的环境，高版本（python 3.7.4）应该是可以用的，我把lxml的依赖添加到requirements.txt中了，感谢提出建议^^

**Comment by BobAnkh** [comment]
感谢您做出更好的修改，那么我就把这个issue关闭了~
