### ISSUE TITLE
北邮人新改版更新#29后出现新报错

### ISSUE THREAD

**Issue by Dong-Guan-Saohuang-Dadui** [lipssmycode/byrbt_bot#31]
byrbt_bot-bot-1  | [ERROR] AttributeError("'NoneType' object has no attribute 'attrs'")
byrbt_bot-bot-1  | failed to parse torrent table!
byrbt_bot-bot-1  | 退出
byrbt_bot-bot-1  | 保存数据
byrbt_bot-bot-1  | /conda/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:30: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
byrbt_bot-bot-1  | Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
byrbt_bot-bot-1  |   method='lar', copy_X=True, eps=np.finfo(np.float).eps,
byrbt_bot-bot-1  | /conda/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:167: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
byrbt_bot-bot-1  | Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
byrbt_bot-bot-1  |   method='lar', copy_X=True, eps=np.finfo(np.float).eps,
byrbt_bot-bot-1  | /conda/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:284: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
byrbt_bot-bot-1  | Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
byrbt_bot-bot-1  |   eps=np.finfo(np.float).eps, copy_Gram=True, verbose=0,
byrbt_bot-bot-1  | /conda/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:862: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
byrbt_bot-bot-1  | Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
byrbt_bot-bot-1  |   eps=np.finfo(np.float).eps, copy_X=True, fit_path=True,
byrbt_bot-bot-1  | /conda/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:1101: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
byrbt_bot-bot-1  | Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
byrbt_bot-bot-1  |   eps=np.finfo(np.float).eps, copy_X=True, fit_path=True,
byrbt_bot-bot-1  | /conda/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:1127: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
byrbt_bot-bot-1  | Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
byrbt_bot-bot-1  |   eps=np.finfo(np.float).eps, positive=False):
byrbt_bot-bot-1  | /conda/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:1362: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
byrbt_bot-bot-1  | Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
byrbt_bot-bot-1  |   max_n_alphas=1000, n_jobs=None, eps=np.finfo(np.float).eps,
byrbt_bot-bot-1  | /conda/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:1602: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
byrbt_bot-bot-1  | Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
byrbt_bot-bot-1  |   max_n_alphas=1000, n_jobs=None, eps=np.finfo(np.float).eps,
byrbt_bot-bot-1  | /conda/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:1738: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
byrbt_bot-bot-1  | Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
byrbt_bot-bot-1  |   eps=np.finfo(np.float).eps, copy_X=True, positive=False):
byrbt_bot-bot-1  | /conda/lib/python3.7/site-packages/sklearn/base.py:306: UserWarning: Trying to unpickle estimator NuSVC from version 0.19.1 when using version 0.21.3. This might lead to breaking code or invalid results. Use at your own risk.

**Comment by lipssmycode** [comment]
变化还真是大，切换回去网站风格能不能解决？

**Comment by Dong-Guan-Saohuang-Dadui** [comment]
> 

遗憾，试过了不行

**Comment by lipssmycode** [comment]
#32

**Comment by lipssmycode** [comment]
有好心人修理了，可以试试看，我目前没有网络环境，不太好修理
