### ISSUE TITLE
北邮人改版后报错

### ISSUE THREAD

**Issue by Dong-Guan-Saohuang-Dadui** [lipssmycode/byrbt_bot#33]
byrbt_bot-bot-1  | scan torrent list...
byrbt_bot-bot-1  | [ERROR] AttributeError("'NoneType' object has no attribute 'select_one'")
byrbt_bot-bot-1  | free torrent list：
byrbt_bot-bot-1  | available torrent list：

**Comment by sydxsty** [comment]
> byrbt_bot-bot-1 | scan torrent list... byrbt_bot-bot-1 | [ERROR] AttributeError("'NoneType' object has no attribute 'select_one'") byrbt_bot-bot-1 | free torrent list： byrbt_bot-bot-1 | available torrent list：

fixed in #34 目前还在测试, 跑了一天好像没啥bug

**Comment by Dong-Guan-Saohuang-Dadui** [comment]
> > byrbt_bot-bot-1 | scan torrent list... byrbt_bot-bot-1 | [ERROR] AttributeError("'NoneType' object has no attribute 'select_one'") byrbt_bot-bot-1 | free torrent list： byrbt_bot-bot-1 | available torrent list：
> 
> fixed in #34 目前还在测试, 跑了一天好像没啥bug

大佬好，你确定现在目前可以正常跑吗，我用你的commit好像还是不行，一样的报错

**Comment by sydxsty** [comment]
> > > byrbt_bot-bot-1 | scan torrent list... byrbt_bot-bot-1 | [ERROR] AttributeError("'NoneType' object has no attribute 'select_one'") byrbt_bot-bot-1 | free torrent list： byrbt_bot-bot-1 | available torrent list：
> > 
> > 
> > fixed in #34 目前还在测试, 跑了一天好像没啥bug
> 
> 大佬好，你确定现在目前可以正常跑吗，我用你的commit好像还是不行，一样的报错

后天论文DDL, 等搞完了我看看

**Comment by sydxsty** [comment]
> > > byrbt_bot-bot-1 | scan torrent list... byrbt_bot-bot-1 | [ERROR] AttributeError("'NoneType' object has no attribute 'select_one'") byrbt_bot-bot-1 | free torrent list： byrbt_bot-bot-1 | available torrent list：
> > 
> > 
> > fixed in #34 目前还在测试, 跑了一天好像没啥bug
> 
> 大佬好，你确定现在目前可以正常跑吗，我用你的commit好像还是不行，一样的报错

改好了, 但是因为是去年的代码, 好像改了一些没用的地方, 刚才试了一下能用就没管, 你可以把没必要改的地方还原回去
