### ISSUE TITLE
Feature Request：下载空间限制

### ISSUE THREAD

**Issue by BobAnkh** [lipssmycode/byrbt_bot#4]
我想询问是否有或者可以添加关于自动下种空间的限制？即，可以通过一个参数限制byrbt_bot下载的种子的总大小基本不会超过某一个限制值（基本限制即可），如果某一个种子有可能使得下载总量突破该阈值则放弃该种子的下载。这个参数可以手动设置。我认为，这个参数的设置有利于其的使用，包括我可以手动划定空间用于下载，而不至于占据过多的空间而影响其他方面的工作和内容，其次我已经遇到了下载的种子的大小远大于试验用服务器的存储总量，这会使得整个服务器出现问题。

感谢！

**Comment by lipssmycode** [comment]
目前我用的服务器空间是稍微比较大的（8T），我的限制是下载1G以上1T一下的种子，这样刷流也比较有效，如果空间太小可以手动在代码里面加一下总大小限制，最近比较忙，这边就不加了，欢迎贡献代码 v

**Comment by TTTPOB** [comment]
嗐，这有一个[项目](https://github.com/jerrymakesjelly/autoremove-torrents)我一直在用的

**Comment by BobAnkh** [comment]
> > 我想询问是否有或者可以添加关于自动下种空间的限制？即，可以通过一个参数限制byrbt_bot下载的种子的总大小基本不会超过某一个限制值（基本限制即可），如果某一个种子有可能使得下载总量突破该阈值则放弃该种子的下载。这个参数可以手动设置。我认为，这个参数的设置有利于其的使用，包括我可以手动划定空间用于下载，而不至于占据过多的空间而影响其他方面的工作和内容，其次我已经遇到了下载的种子的大小远大于试验用服务器的存储总量，这会使得整个服务器出现问题。
> > 感谢！
> 
> [WhymustIhaveaname/byrbt_bot](https://github.com/WhymustIhaveaname/byrbt_bot) 我这个分支加了这个功能

非常感谢！
