### ISSUE TITLE
不能下载种子，会报login failed

### ISSUE THREAD

**Issue by likecreep** [lipssmycode/byrbt_bot#8]
你好，正确设置后，能爬取到北邮人的种子列表，也能筛选种子，但是筛选出种子后无法下载，持续报错如下：
[BYRBT].Metro#Exodus#-#Enhanced#Edition#v3.0.7.24#(64bit)#(46543)#[GOG].torrent
login failed
find ByrbtCookies.pickle, loading cookies
[BYRBT].Metro#Exodus#-#Enhanced#Edition#v3.0.7.24#(64bit)#(46543)#[GOG].torrent
login failed
find ByrbtCookies.pickle, loading cookies
[BYRBT].Metro#Exodus#-#Enhanced#Edition#v3.0.7.24#(64bit)#(46543)#[GOG].torrent
login failed
find ByrbtCookies.pickle, loading cookies
[BYRBT].Metro#Exodus#-#Enhanced#Edition#v3.0.7.24#(64bit)#(46543)#[GOG].torrent
login failed
find ByrbtCookies.pickle, loading cookies
[BYRBT].Metro#Exodus#-#Enhanced#Edition#v3.0.7.24#(64bit)#(46543)#[GOG].torrent
login failed
find ByrbtCookies.pickle, loading cookies

**Comment by likecreep** [comment]
上一个错误解决了，是由于没有设置存放torrent文件的文件夹导致。 但是设置文件夹路径后依然报错。
sh: 1: Syntax error: "(" unexpected
script `transmission-remote  -a /root/downloads/byrbt_bot-master/[BYRBT].Metro#Exodus#-#Enhanced#Edition#v3.0.7.24#(64bit)#(46543)#[GOG].torrent` returns 512

**Comment by likecreep** [comment]
找到原因了，由于执行命令时，种子文件名包含(导致命令执行失败，
把原代码里的`transmission-remote -n "{}" -a {}'` 修改为 `transmission-remote -n "{}" -a "{}"'` 就 成功执行了。

**Comment by lipssmycode** [comment]
好的，感谢debug，我修改一下
